# -- 코드를 입력하세요
SELECT A.ANIMAL_ID,B.ANIMAL_TYPE,B.NAME
FROM (
SELECT ANIMAL_ID,ANIMAL_TYPE,NAME,SEX_UPON_INTAKE
FROM ANIMAL_INS 
WHERE SEX_UPON_INTAKE IN('Intact Male','Intact Female'))A
JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID=B.ANIMAL_ID
AND B.SEX_UPON_OUTCOME IN('Neutered Male','Spayed Female')
ORDER BY ANIMAL_ID