-- 코드를 입력하세요
SELECT DISTINCT A.CAR_ID 
# ,DATE_FORMAT(B.START_DATE,'%Y-%m')
FROM CAR_RENTAL_COMPANY_CAR A LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID = B.CAR_ID
WHERE A.CAR_TYPE = '세단' 
AND DATE_FORMAT(B.START_DATE,'%Y-%m') = '2022-10'
ORDER BY CAR_ID DESC
