-- 코드를 입력하세요
SELECT b.BOOK_ID, a.AUTHOR_NAME, 
DATE_FORMAT(b.PUBLISHED_DATE,"%Y-%m-%d") as PUBLISHED_DATE
# ,b.CATEGORY,a.AUTHOR_ID
from AUTHOR a join BOOK b
on b.AUTHOR_ID = a.AUTHOR_ID
where b.CATEGORY = "경제"
order by PUBLISHED_DATE