-- 코드를 작성해주세요
SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D
where D.SKILL_CODE & (SELECT `CODE` FROM SKILLCODES WHERE NAME = 'Python')
or D.SKILL_CODE & (SELECT `CODE` FROM SKILLCODES WHERE NAME = 'C#')
ORDER BY ID

