-- 코드를 입력하세요


SELECT C.ANIMAL_ID,C.NAME
FROM (SELECT B.ANIMAL_ID,B.NAME,DATEDIFF(B.DATETIME,A.DATETIME)AS 보호기간
FROM ANIMAL_INS A JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY 보호기간 DESC
LIMIT 2) C