-- 코드를 작성해주세요
SELECT A.ID
FROM ECOLI_DATA A 
LEFT JOIN ECOLI_DATA B
    ON A.PARENT_ID = B.ID
LEFT JOIN ECOLI_DATA C
    ON B.PARENT_ID = C.ID
WHERE B.PARENT_ID IS NOT NULL
    AND C.PARENT_ID IS NULL
ORDER BY A.ID

